version: '3'

services:
  web:
    container_name: debio-genetic-analyst-ui
    image: debionetwork/debio-genetic-analyst-ui
    build:
      context: ../../
      dockerfile: .maintain/docker/Dockerfile
    env_file:
      - ../../.env
    environment:
      - HOST=0.0.0.0
      - PORT=80
    ports:
      - 8085:80
    networks:
      debio:
        ipv4_address: 172.27.1.5
        aliases:
          - debio-genetic-analyst-ui

networks:
  debio:
    external: true
